apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  application.yml: |
    spring:
      profiles:
        active: prod
      datasource:
        url: jdbc:mysql://mysql-service:3306/ecommerce_prod
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
      redis:
        host: redis-service
        port: 6379
      kafka:
        bootstrap-servers: kafka-service:9092
    
    server:
      port: 8080
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
    
    logging:
      level:
        com.ecommerce: INFO
        org.springframework.security: WARN