spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/ecommerce_prod}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  level:
    com.ecommerce: INFO
    org.springframework.security: WARN
  file:
    name: /var/log/ecommerce/app.log

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics