spring:
  datasource:
    url: jdbc:h2:mem:ecommerce_db
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    
  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ecommerce-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: myVeryLongSecretKeyThatIsAtLeast256BitsLongForJWTSecurity123456789
  expiration: 86400000

server:
  port: 8080

logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG